# Generated by Django 2.2 on 2019-05-09 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190508_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='allergies',
            field=models.CharField(default='No Info', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_pressure',
            field=models.CharField(default='No Info', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='overall_body_test',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='task_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 9, 17, 49, 8, 423365)),
        ),
    ]
