# Generated by Django 2.2.1 on 2019-05-10 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190509_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='description',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 23, 23, 40, 621116)),
        ),
    ]
