# Generated by Django 2.2.1 on 2019-05-10 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190510_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='overall_body_test',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 3, 39, 14, 177917)),
        ),
    ]
