# Generated by Django 2.2.1 on 2019-05-19 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190513_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='photo_link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 19, 23, 42, 23, 253995)),
        ),
    ]
