# Generated by Django 3.2 on 2021-04-24 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190523_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 13, 23, 42, 832406)),
        ),
    ]
